package webserviceservices.user;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-07-13T20:51:02.001-03:00
 * Generated source version: 3.3.7
 *
 */
@WebServiceClient(name = "UserService",
                  wsdlLocation = "file:/home/evandroig/Projects/WebService/src/main/resources/wsdl/UserService.wsdl",
                  targetNamespace = "webserviceservices/User/")
public class UserService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("webserviceservices/User/", "UserService");
    public final static QName UserPort = new QName("webserviceservices/User/", "UserPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/evandroig/Projects/WebService/src/main/resources/wsdl/UserService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/home/evandroig/Projects/WebService/src/main/resources/wsdl/UserService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public UserService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UserService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UserService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns UserService
     */
    @WebEndpoint(name = "UserPort")
    public UserService getUserPort() {
        return super.getPort(UserPort, UserService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserService
     */
    @WebEndpoint(name = "UserPort")
    public UserService getUserPort(WebServiceFeature... features) {
        return super.getPort(UserPort, UserService.class, features);
    }

}
